# Parameters
total-days: 100

# Interface
gui:
  title: "&6DailyRewards &7(Page {page}/{max})"
  navigation:
    previous: "&aPrevious Page"
    next: "&aNext Page"

# Messages
messages:
  claim-success: "&aYou have claimed the reward for day {day}!"
  invalid-order: "&cYou must claim the days in order!"
  wait-message: "&eCome back in {time} hours!"





# money: "none" - Disable the currency system
# money: "vault" - Use the Vault currency system (EssentialsX)
# money: "PlayerPoints" - Use PlayerPoints
# money: "CoinsEngine" - Use CoinsEngine
# money: "ultraeconomy" - Use UltraEconomy
# ultraeconomy:
#   currency: "default" # Name of the currency (default: default)
# money: "VotingPlugin" - Use VotingPlugin

money: "vault"  # Default: Vault (EssentialsX)



# reward
rewards:
  day-1:
    - "give {player} diamond 1"
    - "give {player} bread 5"
  day-2:
    - "give {player} iron_ingot 3"
  day-7:
    - "give {player} diamond 1"
    - "give {player} emerald 2"
  day-30:
    - "give {player} diamond_block 1"
    - "give {player} netherite_ingot 1"





reset:
  enabled: true
  delay: 1

ultraeconomy:

  currency: "default"