# Paramètres
total-days: 100

# Interface
gui:
  title: "&6DailyRewardss &7(Page {page}/{max})"
  navigation:
    previous: "&aPage précédente"
    next: "&aPage suivante"

# Messages
messages:
  claim-success: "&aVous avez réclamé la récompense du jour {day} !"
  invalid-order: "&cVous devez réclamer les jours dans l'ordre !"
  wait-message: "&eRevenez dans {time} heures !"





# money: "none" - Disable the currency system
# money: "vault" - Use the Vault currency system (EssentialsX)
# money: "PlayerPoints" - Use PlayerPoints
# money: "CoinsEngine" - Use CoinsEngine
# money: "ultraeconomy" - Use UltraEconomy
# ultraeconomy:
#   currency: "default" # Name of the currency (default: default)
# money: "VotingPlugin" - Use VotingPlugin

money: "vault"  # Default: Vault (EssentialsX)



# reward
rewards:
  day-1:
    - "give {player} diamond 1"
    - "give {player} bread 5"
  day-2:
    - "give {player} iron_ingot 3"
  day-7:
    - "give {player} diamond 1"
    - "give {player} emerald 2"
  day-30:
    - "give {player} diamond_block 1"
    - "give {player} netherite_ingot 1"





reset:
  enabled: true
  delay: 1

ultraeconomy:

  currency: "default"